# Helm values for hcloud-csi (chart version in kustomization.yaml)
# To regenerate the manifest:
#   cd upup/models/cloudup/resources/addons/hcloud-csi-driver.addons.k8s.io
#   ./regenerate.sh

controller:
  podDisruptionBudget:
    create: false

node:
  tolerations:
    - effect: NoExecute
      operator: Exists
    - effect: NoSchedule
      operator: Exists
    - key: CriticalAddonsOnly
      operator: Exists

metrics:
  enabled: true
